<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

acf_add_local_field_group( array(
	'key' => 'group_63324f1409f11',
	'title' => 'Overlay Hero',
	'fields' => array(
		array(
			'key' => 'field_63324f2f4cc91',
			'label' => 'Context',
			'name' => 'context',
			'aria-label' => '',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_62eff83a5aa1e',
			),
			'display' => 'seamless',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 0,
		),
		array(
			'key' => 'field_63324f634cc92',
			'label' => 'Video Loop',
			'name' => 'video_loop',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
		array(
			'key' => 'field_overlay_hero_use_device_specific_video_files',
			'label' => 'Use Device Specific Video Files',
			'name' => 'use_device_specific_video_files',
			'type' => 'true_false',
			'instructions' => 'Show optional tablet and mobile MP4 video loop fields.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
		array(
			'key' => 'field_681d185e7a101',
			'label' => 'Tablet Video Loop',
			'name' => 'video_loop_tablet',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Optional smaller MP4 loop for tablet-sized screens. Falls back to the main video loop when empty.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_overlay_hero_use_device_specific_video_files',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
		array(
			'key' => 'field_681d185e7a102',
			'label' => 'Mobile Video Loop',
			'name' => 'video_loop_mobile',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Optional compressed MP4 loop for mobile screens. Leave empty to show the poster image only on mobile.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_overlay_hero_use_device_specific_video_files',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
		array(
			'key' => 'field_overlay_hero_optimize_with_cloudflare_streams',
			'label' => 'Optimize with Cloudflare Stream',
			'name' => 'optimize_with_cloudflare_streams',
			'type' => 'true_false',
			'instructions' => 'Show HLS manifest fields for Cloudflare Stream playback.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		),
		array(
			'key' => 'field_681d2d5d03901',
			'label' => 'HLS Video Loop Manifest',
			'name' => 'hls_video_loop',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Optional desktop/default .m3u8 manifest URL. Used before MP4 loop fields.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_overlay_hero_optimize_with_cloudflare_streams',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_681d2d5d03902',
			'label' => 'HLS Tablet Video Loop Manifest',
			'name' => 'hls_video_loop_tablet',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Optional tablet-specific .m3u8 manifest URL. Falls back to the default HLS manifest when empty.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_overlay_hero_optimize_with_cloudflare_streams',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_681d2d5d03903',
			'label' => 'HLS Mobile Video Loop Manifest',
			'name' => 'hls_video_loop_mobile',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Optional mobile-specific .m3u8 manifest URL. Falls back to the default HLS manifest when empty.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_overlay_hero_optimize_with_cloudflare_streams',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_63324f924cc93',
			'label' => 'Image',
			'name' => 'image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'Hero',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_634839089c474',
			'label' => 'Video',
			'name' => 'video',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_63483a5e9c475',
					'label' => 'ID',
					'name' => 'id',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/overlay-hero',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

endif;
