<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

acf_add_local_field_group( array(
  'key' => 'group_632bc0afc1557',
  'title' => 'Article Grid',
  'fields' => array(
    array(
      'key' => 'field_66a797e74888c',
      'label' => 'Display Posts Method',
      'name' => 'display_posts_method',
      'aria-label' => '',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'internal' => 'Internal Posts',
        'api' => 'External API',
        'manual' => 'Add Posts Manually',
      ),
      'default_value' => false,
      'return_format' => 'value',
      'multiple' => 0,
      'allow_null' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
    ),
    array(
      'key' => 'field_68abcdefstyle',
      'label' => 'Style',
      'name' => 'style',
      'aria-label' => '',
      'type' => 'radio',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'manual',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'default' => 'Default',
        'accordion' => 'Accordion',
      ),
      'default_value' => 'default',
      'return_format' => 'value',
      'layout' => 'horizontal',
      'allow_null' => 0,
      'other_choice' => 0,
      'save_other_choice' => 0,
      'parent_repeater' => 'field_632bc10d2e53d',
    ),
    array(
      'key' => 'field_632bc10d2e53d',
      'label' => 'Items',
      'name' => 'items',
      'aria-label' => '',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'manual',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'block',
      'pagination' => 0,
      'min' => 0,
      'max' => 0,
      'collapsed' => '',
      'button_label' => 'Add Item',
      'rows_per_page' => 20,
      'sub_fields' => array(
        array(
          'key' => 'field_632bc1442e53f',
          'label' => 'Image',
          'name' => 'image',
          'aria-label' => '',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
          'preview_size' => 'Square_mobile',
          'parent_repeater' => 'field_632bc10d2e53d',
        ),
        array(
          'key' => 'field_632bc12c2e53e',
          'label' => 'Context',
          'name' => 'context',
          'aria-label' => '',
          'type' => 'clone',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'clone' => array(
            0 => 'group_62eff83a5aa1e',
          ),
          'display' => 'seamless',
          'layout' => 'block',
          'prefix_label' => 0,
          'prefix_name' => 0,
          'parent_repeater' => 'field_632bc10d2e53d',
        ),
        array(
          'key' => 'field_63436659a7bb2',
          'label' => 'Post',
          'name' => 'post',
          'type' => 'post_object',
          'instructions' => 'Automatically populate this article item with post content from within the site. Selecting this option will override manually selected image and context above when displayed on the front-end.',
          'required' => 0,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_68abcdefstyle', // Style field
                'operator' => '==',
                'value' => 'default',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => '',
          'taxonomy' => '',
          'return_format' => 'object',
          'multiple' => 0,
          'allow_null' => 0,
          'ui' => 1,
          'parent_repeater' => 'field_632bc10d2e53d',
          'bidirectional_target' => array(),
        ),
      ),
    ),
    array(
      'key' => 'field_64dba9a5f0522',
      'label' => 'API Source',
      'name' => 'api_source',
      'aria-label' => '',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'api',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'media_coverage' => 'News - Media Coverage',
      ),
      'default_value' => 'media_coverage',
      'return_format' => 'value',
      'multiple' => 0,
      'allow_null' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
    ),
    array(
      'key' => 'field_639cbcc9175ec',
      'label' => 'Media Coverage Type (Tag)',
      'name' => 'external_media_api',
      'aria-label' => '',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_64dba9a5f0522',
            'operator' => '==',
            'value' => 'media_coverage',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'all_media' => 'All Media Coverage',
        'highlight' => 'Highlights',
        'president' => 'Office of the President Media Coverage',
      ),
      'default_value' => false,
      'return_format' => 'value',
      'multiple' => 0,
      'allow_null' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
    ),
    array(
      'key' => 'field_64dbd04266c9e',
      'label' => 'Number of Posts',
      'name' => 'range',
      'aria-label' => '',
      'type' => 'range',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'api',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 5,
      'min' => 3,
      'max' => 25,
      'step' => '',
      'prepend' => '',
      'append' => '',
    ),
    array(
      'key' => 'field_6344542af7223',
      'label' => 'Size',
      'name' => 'size',
      'aria-label' => '',
      'type' => 'radio',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'manual',
          ),
        ),
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'api',
          ),
        ),
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'internal',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'small' => 'Small',
        'xsmall' => 'X-Small',
      ),
      'default_value' => '',
      'return_format' => 'value',
      'allow_null' => 0,
      'other_choice' => 0,
      'layout' => 'horizontal',
      'save_other_choice' => 0,
    ),
    array(
      'key' => 'field_632bc0d32e53c',
      'label' => 'Columns',
      'name' => 'columns',
      'aria-label' => '',
      'type' => 'radio',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'manual',
          ),
        ),
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'api',
          ),
        ),
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'internal',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        2 => '2',
        3 => '3',
        4 => '4',
      ),
      'default_value' => '',
      'return_format' => 'value',
      'allow_null' => 0,
      'other_choice' => 0,
      'layout' => 'horizontal',
      'save_other_choice' => 0,
    ),
    array(
      'key' => 'field_632bc98b58a51',
      'label' => 'Image Orientation',
      'name' => 'image_orientation',
      'aria-label' => '',
      'type' => 'radio',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'manual',
          ),
        ),
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'api',
          ),
        ),
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'internal',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array(
        'rectangle' => 'Rectangle',
        'square' => 'Square',
        'portrait' => 'Portrait',
      ),
      'default_value' => '',
      'return_format' => 'value',
      'allow_null' => 0,
      'other_choice' => 0,
      'layout' => 'horizontal',
      'save_other_choice' => 0,
    ),
    array(
      'key' => 'field_63446eb11e773',
      'label' => 'Border',
      'name' => 'border',
      'aria-label' => '',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'manual',
          ),
        ),
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'api',
          ),
        ),
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'internal',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
    ),
    array(
      'key' => 'field_63571df95ae3e',
      'label' => 'Render Posts Category',
      'name' => 'render_posts_category',
      'aria-label' => '',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'internal',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'category',
      'add_term' => 0,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'id',
      'field_type' => 'radio',
      'allow_null' => 0,
      'multiple' => 0,
      'bidirectional_target' => array(
      ),
    ),
    array(
      'key' => 'field_6682ca3641df8',
      'label' => 'Post Limit',
      'name' => 'post_limit',
      'aria-label' => '',
      'type' => 'number',
      'instructions' => '-1 indicates no limit',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'internal',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => -1,
      'min' => -1,
      'max' => 99999,
      'placeholder' => '',
      'step' => '',
      'prepend' => '',
      'append' => '',
    ),
    array(
      'key' => 'field_674dd19648dec',
      'label' => 'Exclude Posts',
      'name' => 'exclude_internal_posts',
      'aria-label' => '',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_66a797e74888c',
            'operator' => '==',
            'value' => 'internal',
          ),
        ),
      ),
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'table',
      'pagination' => 0,
      'min' => 0,
      'max' => 0,
      'collapsed' => '',
      'button_label' => 'Add Row',
      'rows_per_page' => 20,
      'sub_fields' => array(
        array(
          'key' => 'field_674dd1eb48ded',
          'label' => 'Post',
          'name' => 'post',
          'aria-label' => '',
          'type' => 'post_object',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'post_type' => array(
            0 => 'post',
          ),
          'post_status' => array(
            0 => 'publish',
          ),
          'taxonomy' => '',
          'return_format' => 'object',
          'multiple' => 0,
          'allow_null' => 0,
          'bidirectional' => 0,
          'ui' => 1,
          'bidirectional_target' => array(
          ),
          'parent_repeater' => 'field_674dd19648dec',
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'block',
        'operator' => '==',
        'value' => 'acf/article-grid',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
  'show_in_rest' => 0,
) );

endif;