export const WysiwygClasses = [
    '[&_h2]:font-extended',
    '[&_h2]:font-normal',
    '[&_h2]:text-24',
    '[&_h2]:leading-110',
    '[&_h2]:-tracking-3',
    '[&_h2]:text-indigo',

    '[&_h3]:font-extended',
    '[&_h3]:font-bold',
    '[&_h3]:text-18',
    '[&_h3]:text-indigo',

    '[&_h4]:font-extended',
    '[&_h4]:font-normal',
    '[&_h4]:text-20',
    '[&_h4]:leading-110',
    '[&_h4]:-tracking-3',
    '[&_h4]:text-indigo',

    '[&_h5]:font-extended',
    '[&_h5]:font-bold',
    '[&_h5]:text-14',
    '[&_h5]:leading-130',
    '[&_h5]:tracking-8',
    '[&_h5]:text-azure',
    '[&_h5]:uppercase',

    '[&_h6]:font-extended',
    '[&_h6]:font-bold',
    '[&_h6]:text-12',
    '[&_h6]:tracking-8',
    '[&_h6]:text-azure',
    '[&_h6]:uppercase',

    '[&_p]:font-body',
    '[&_p]:mb-4',
    '[&_p]:font-normal',
    '[&_p]:leading-[1.5]',
    '[&_p]:text-indigo-800',
    '[&_p>a]:underline',
    '[&_p>a:hover]:no-underline',
    '[&_p>a:hover]:[&_p>a]:text-indigo',

    '[&_ul]:pl-6',
    '[&_ul]:mb-4',
    '[&_ol]:pl-6',
    '[&_ol]:mb-4',
    '[&_ul>li]:font-body', 
    '[&_ul>li]:font-normal', 
    '[&_ul>li]:text-16', 
    '[&_ul>li]:leading-130', 
    '[&_ul>li]:text-indigo-800', 
    '[&_ul>li]:list-disc', 
    '[&_ul>li]:list-outside', 
    '[&_ul>li]:ml-3', 
    '[&_ul>li+li]:mt-2',
    '[&_ul>li+ul]:mt-2',
    '[&_ul>li>a]:underline', 
    '[&_ul>li>a:hover]:no-underline', 
    '[&_ul>li>a:hover]:text-indigo',
    
    '[&_ol+h2]:mt-20',
    '[&_ol>li]:font-body', 
    '[&_ol>li]:font-normal', 
    '[&_ol>li]:text-16', 
    '[&_ol>li]:leading-130', 
    '[&_ol>li]:text-indigo-800', 
    '[&_ol>li]:list-decimal', 
    '[&_ol>li]:list-outside', 
    '[&_ol>li]:ml-3', 
    '[&_ol>li+li]:mt-2',
    '[&_ol>li+ol]:mt-2',
    '[&_ol>li>a]:underline', 
    '[&_ol>li>a:hover]:no-underline', 
    '[&_ol>li>a:hover]:text-indigo',

    '[&_div+div]:mt-20', 
    'md:[&_div+div]:mt-[100px]', 
    '[&_div+figure]:mt-20', 
    'md:[&_div+figure]:mt-[100px]', 
    '[&_div+h2]:mt-16', 
    'md:[&_div+h2]:mt-20',
    '[&_figure+figure]:mt-20', 
    'md:[&_figure+figure]:mt-[100px]', 
    '[&_figure+div]:mt-20', 
    'md:[&_figure+div]:mt-[100px]', 
    '[&_figure+h2]:mt-16', 
    'md:[&_figure+h2]:mt-20',
    '[&_p+div]:mt-10', 
    'md:[&_p+div]:mt-[50px]', 
    '[&_p+h2]:mt-20', 
    '[&_p+h3]:mt-6', 
    '[&_p+p]:mt-6', 
    '[&_p+ul]:mt-6', 
    '[&_p+table]:mt-10', 
    'md:[&_p+table]:mt-[50px]',
    '[&_hr]:border-t', 
    '[&_hr]:border-solid', 
    '[&_hr]:border-indigo-300', 
    '[&_hr]:my-16',
  ].join(' ');
