<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

  acf_add_local_field_group(array(
		'key' => 'group_645b8ea54f2e1',
		'title' => 'List Block Grid',
		'fields' => array(
			array(
				'key' => 'field_645b8e9e57787',
				'label' => 'Columns',
				'name' => 'columns',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					2 => '2',
					3 => '3',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'layout' => 'horizontal',
			),
			array(
				'key' => 'field_645b8f0f57788',
				'label' => 'Type',
				'name' => 'type',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'light' => 'Light',
					'dark' => 'Dark',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'layout' => 'horizontal',
			),
			array(
				'key' => 'field_645b8f3557789',
				'label' => 'Items',
				'name' => 'items',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Item',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_645b8f575778a',
						'label' => 'Context',
						'name' => 'context',
						'aria-label' => '',
						'type' => 'clone',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'clone' => array(
							0 => 'group_62eff83a5aa1e',
						),
						'display' => 'seamless',
						'layout' => 'block',
						'prefix_label' => 0,
						'prefix_name' => 0,
						'parent_repeater' => 'field_645b8f3557789',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/list-block-grid',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

endif;