<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

acf_add_local_field_group( array(
	'key' => 'group_632cb9bac13b2',
	'title' => 'Table',
	'fields' => array(
		array(
			'key' => 'field_632cb9cfb5ff9',
			'label' => 'Render API',
			'name' => 'render_api',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_632dceddb1f59',
			'label' => 'API',
			'name' => 'api',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_632cb9cfb5ff9',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Majors and Minors' => 'Majors and Minors',
				'Department Courses' => 'Department Courses',
				'Course Catalogue' => 'Course Catalogue',
				'Departments' => 'Departments',
				'Offices' => 'Offices',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'horizontal',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_632cbb90b5ffa',
			'label' => 'Department Code',
			'name' => 'department_code',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_632cb9cfb5ff9',
						'operator' => '==',
						'value' => '1',
					),
					array(
						'field' => 'field_632dceddb1f59',
						'operator' => '==',
						'value' => 'Department Courses',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'AFAM' => 'African American Studies',
				'AMER' => 'American Studies',
				'ART' => 'Art',
				'PHYS' => 'Physics and Astronomy',
				'ANTH' => 'Anthropology',
				'BICH' => 'Biology/Chemistry',
				'BIOL' => 'Biology',
				'BGLW' => 'Bigelow Laboratory for Ocean Sciences',
				'CHEM' => 'Chemistry',
				'CINE' => 'Cinema Studies',
				'FRIT' => 'French and Italian',
				'CLAS' => 'Classics',
				'EAST' => 'East Asian Studies',
				'COMP' => 'Computer Science',
				'ECON' => 'Economics',
				'EDUC' => 'Education',
				'ENGL' => 'English',
				'ENVS' => 'Environmental Studies',
				'ERSC' => 'Earth Sciences',
				'GMRU' => 'German and Russian',
				'GOVT' => 'Government',
				'GLST' => 'Global Studies',
				'JWST' => 'Jewish Studies',
				'HIST' => 'History',
				'INDP' => 'Independent Studies',
				'ISP' => 'Integrated Studies Program',
				'JNPL' => 'January Courses',
				'LTAM' => 'Latin American Studies',
				'MATH' => 'Math',
				'HUMA' => 'Humanities',
				'MUSI' => 'Music',
				'PHIL' => 'Philosophy',
				'PSYC' => 'Psychology',
				'RELG' => 'Religious Studies',
				'STAT' => 'Statistics',
				'SOCY' => 'Sociology',
				'SPAN' => 'Spanish',
				'SCIT' => 'Science, Technology, and Society',
				'THEA' => 'Theater and Dance',
				'WGST' => 'Women\'s, Gender, and Sexuality Studies',
				'WRT' => 'Writing Program',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6330a6eea744b',
			'label' => 'Items Per Page',
			'name' => 'items_per_page',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_632cb9cfb5ff9',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_632cbc54b5ffb',
			'label' => 'Headings',
			'name' => 'headings',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_632cb9cfb5ff9',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Heading',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_632cbc74b5ffc',
					'label' => 'Heading',
					'name' => 'heading',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_632cbc54b5ffb',
				),
			),
		),
		array(
			'key' => 'field_632cbc7eb5ffd',
			'label' => 'Items',
			'name' => 'items',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_632cb9cfb5ff9',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Item',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_632cbc99b5ffe',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_632cbc7eb5ffd',
								'operator' => '==empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'Square_mobile',
					'parent_repeater' => 'field_632cbc7eb5ffd',
				),
				array(
					'key' => 'field_632cf449d16ce',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_632cbc7eb5ffd',
				),
				array(
					'key' => 'field_632cbcaab5fff',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'parent_repeater' => 'field_632cbc7eb5ffd',
				),
				array(
					'key' => 'field_632cbcdfb6000',
					'label' => 'Columns',
					'name' => 'columns',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Column',
					'rows_per_page' => 20,
					'parent_repeater' => 'field_632cbc7eb5ffd',
					'sub_fields' => array(
						array(
							'key' => 'field_63912ad3fadb7',
							'label' => 'Link or Text',
							'name' => 'link_or_text',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'link' => 'Link',
								'text' => 'Text',
							),
							'default_value' => 'text',
							'return_format' => 'value',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
							'parent_repeater' => 'field_632cbcdfb6000',
						),
						array(
							'key' => 'field_632cbcecb6001',
							'label' => 'Column',
							'name' => 'column',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_63912ad3fadb7',
										'operator' => '==',
										'value' => 'text',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_632cbcdfb6000',
						),
						array(
							'key' => 'field_63912b38fadb8',
							'label' => 'Link',
							'name' => 'link',
							'aria-label' => '',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_63912ad3fadb7',
										'operator' => '==',
										'value' => 'link',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'parent_repeater' => 'field_632cbcdfb6000',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/table',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

endif;