<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

acf_add_local_field_group( array(
	'key' => 'group_62efce9109988',
	'title' => 'Home Hero',
	'fields' => array(
		array(
			'key' => 'field_62efce910cb19',
			'label' => 'Heading',
			'name' => 'heading',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62efce910cb24',
			'label' => 'Caption',
			'name' => 'caption',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62efce910cb29',
			'label' => 'Video',
			'name' => 'video',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
		array(
			'key' => 'field_home_hero_use_device_specific_video_files',
			'label' => 'Use Device Specific Video Files',
			'name' => 'use_device_specific_video_files',
			'type' => 'true_false',
			'instructions' => 'Show optional tablet and mobile MP4 video fields.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
			  'width' => '',
			  'class' => '',
			  'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		  ),
		  
		  
		array(
			'key' => 'field_681d180ef4b01',
			'label' => 'Tablet Video',
			'name' => 'video_tablet',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Optional smaller MP4 for tablet-sized screens. Falls back to the main video when empty.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
					'field' => 'field_home_hero_use_device_specific_video_files',
					'operator' => '==',
					'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
		array(
			'key' => 'field_681d180ef4b02',
			'label' => 'Mobile Video',
			'name' => 'video_mobile',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Optional compressed MP4 for mobile screens. Leave empty to show the poster image only on mobile.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
					'field' => 'field_home_hero_use_device_specific_video_files',
					'operator' => '==',
					'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
		array(
			'key' => 'field_home_hero_optimize_with_cloudflare_streams',
			'label' => 'Optimize with Cloudflare Stream',
			'name' => 'optimize_with_cloudflare_streams',
			'type' => 'true_false',
			'instructions' => 'Show HLS manifest fields for Cloudflare Stream playback.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
			  'width' => '',
			  'class' => '',
			  'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
		  ),
		array(
			'key' => 'field_681d2d01b6201',
			'label' => 'HLS Video Manifest',
			'name' => 'hls_video',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Optional desktop/default .m3u8 manifest URL. Used before MP4 fields.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
					'field' => 'field_home_hero_optimize_with_cloudflare_streams',
					'operator' => '==',
					'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_681d2d01b6202',
			'label' => 'HLS Tablet Video Manifest',
			'name' => 'hls_video_tablet',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Optional tablet-specific .m3u8 manifest URL. Falls back to the default HLS manifest when empty.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
					'field' => 'field_home_hero_optimize_with_cloudflare_streams',
					'operator' => '==',
					'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_681d2d01b6203',
			'label' => 'HLS Mobile Video Manifest',
			'name' => 'hls_video_mobile',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Optional mobile-specific .m3u8 manifest URL. Falls back to the default HLS manifest when empty.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
					'field' => 'field_home_hero_optimize_with_cloudflare_streams',
					'operator' => '==',
					'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_62efce910cb2f',
			'label' => 'Image',
			'name' => 'image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'Hero',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_62efcf81ee734',
			'label' => 'Buttons (copy)',
			'name' => 'buttons_copy',
			'aria-label' => '',
			'type' => 'clone',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'clone' => array(
				0 => 'group_62efae3375c73',
			),
			'display' => 'seamless',
			'layout' => 'block',
			'prefix_label' => 0,
			'prefix_name' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/home-hero',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

endif;
